### ISSUE TITLE
Encryption password could be compromised based on login password

### ISSUE THREAD

**Issue by user6529576559** [standardfile/sfjs#1]
Hi,

I'm not a cryptographer so I'm not 100% confident about this but it seems it is not the best idea to derive the authorization and encryption password from the same master key because if the hash of the auth pwd got compromised (it is stored in the DB) the original auth pwd can be retrieved by brute forcing the hash, then the master key can be brute forced too. It would take a while though...

The Secure Remote Password Protocol can come to the rescue.
Protonmail used to have 2 passwords: one for logging in into the mailbox, and one for decrypting the mailbox. This way the email provider didn't have the knowledge to look into somebody's mail because the encryption password (or any related info like hash) never left the client.
They were able to further simplify their service by only requiring to have 1 password but still provide the same security, more info here:
https://protonmail.com/blog/encrypted_email_authentication/

**Comment by mobitar** [comment]
The whole purpose of one way hash functions _is_ that they take forever to guess. So "brute force" is not used lightly here. But we don't just use a simple hash function. We use PBKDF2, which is specially designed for password hashing, and uses a large cost to offset any advances in hashing power.

**Comment by user6529576559** [comment]
I see, but then I wonder why Protonmail used the technique what they have chosen?

**Comment by mobitar** [comment]
The point of PBKDF2 is to take a user inputted password and stretch it into something more reasonably secure. You can pass any hash cost to that function, such as 500,000, which would take multiple seconds to complete, and the end result will still be a hash of the same size as if 10 iterations were passed instead. So the fact that the result is a hash doesn't mean it's not secure. Brute forcing is feasible when you hash user passwords. It's infeasible when you brute force hashes directly.

**Comment by user6529576559** [comment]
Yes, I know what PBKDF2 is for (also VeraCrypt is using it for the same reason). What I mean that there is no need to brute force PBKDF2. In the DB table, the auth password is stored, hashed of course. If an attacker gets it, it can brute force it, so the original auth password is gained. Then the attacker does a search for this (in the equation, authKey is now known):
`var authKey = SFJS.crypto.hmac256(mk, CryptoJS.enc.Utf8.parse("a").toString(CryptoJS.enc.Hex))`
Where with using mk it is possible to decrypt the notes:
`var encryptionKey = SFJS.crypto.hmac256(mk, CryptoJS.enc.Utf8.parse("e").toString(CryptoJS.enc.Hex));`
Then the notes can be decrypted.

Please, correct me if I'm wrong.
I would also be interested about what is your guessing, why Protonmail doesn't use this way of password handling.

**Comment by mobitar** [comment]
> If an attacker gets it, it can brute force it, so the original auth password is gained

The auth password is hashed using bcrypt on the server side. You can't just brute force these kinds of things. Again brute force typically means guessing your way to a user password, not to a hash.

Now assume that the attacker has spent several centuries "brute forcing" the auth password, hash functions are one-way: you can't go backwards using the result. Unless you spend another several centuries. 

Every system has its own intricacies, and its own advantages and disadvantages for a given design. I can't speak for ProtonMail. I'm not saying the system we use is the _best_ system, since security is a moving target. I'm also not closed off to improving it over time, and if that leads to SRP, then so be it.

**Comment by user6529576559** [comment]
OK, it was just an idea. The current solution is reasonably secure anyways. It is much easier to steal the password from client side by a malicious keyboard (especially in case of android) if somebody really wants it.

**Comment by user6529576559** [comment]
One issue still remains: if the attacker somehow can MiTM the communication between the standardnotes app and the standardfile server, then it is not needed to brute force the bcrypted auth pwd. The connection between the server and client is through HTTPS, but what if somebody self hosts a server and doesn't want to mess with certificates. Well, that's his problem, I know, but it would be more user friendly if the encryption would take place at app level (as it is done now, but I'm not sure about how the auth password is handled). Metadata would be plain text still: content type, approx. content length, created date, updated date, etc.
Also there are several methods to compromise the HTTPS connection (e.g. Turmoil + FoxAcid).

Or is the auth pwd hashed on the client before sending then hashed again on server side to compare?
How many hashings and what kinds are taking place exactly? I mean user enters the password in the browser into a textbox, then what happens to the data (password) step by step. My guess is first PBKDF2 it, then derive auth pwd with HMAC256, then I don't know, there should be a bcrypt on client side, then send it to the web server, then bcrypt again and then compare to the stored value in the DB.

**Comment by mobitar** [comment]
The encryption spec is up here in it's entirety if you want to know how it works: https://standardfile.org/#encryption

**Comment by user6529576559** [comment]
All I can see in standardfile.org is a newsletter signup form. I used archive.org to have a look but I found deprecated info. Then I checked the github source for the page but the info was obsolete too. I can see because for example after the PBKDF2 function the key is simply split by length/2 in the documentation but in the source code HMAC256 is used. There is also no mention about bcrypt on the server side.

Only scenario which I find problematic is when human stupidity comes into action. I mean if somebody's password is in the TOP 10 000 passwords list like "1234" and stuff like that, then if the DB gets pwned, a GPU password cracker can crack the hash in minutes because the DB contains everything: the salt, the password derivation function, iteration count, hash length, and also the resulting auth password. If the auth password is bcrypted and only the DB is pwned and not the whole server then this cannot be used to verify the password but using letter frequency on the decrypted notes could work. But this doesn't even needed because a top passwords dictionary is used and there is incredibly little chance that it is just a hash collision.

So I would suggest to warn the users at signup to use a password management app to generate and store their password for standard notes for two reason, which is basically one:
If they try to remember a complex password, they will forget it.
If they provide a weak password they will risk being pwned.

**Comment by mobitar** [comment]
The site was having some problems yesterday. Try again now. The info there is up to date. Note that there are two encryption types, 001 and 002. 002 is the newest one. It's available on all apps now, but not yet used to actively encrypt, until we're sure most people have that version of the app. Will deploy 002 encryption in a 2-3 months.
