### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by raelb** [standardfile/sfjs#12]
Hello,
I tried running the test suite on Windows with a Standard File Server running on the local machine. I encountered a few failures. Is this to be expected?

Test #1 failures:
![image](https://user-images.githubusercontent.com/13108198/69555984-ae393e00-0fac-11ea-87dd-fb282f9bf2aa.png)

![image](https://user-images.githubusercontent.com/13108198/69556001-b5f8e280-0fac-11ea-8aa0-51168314a90d.png)
![image](https://user-images.githubusercontent.com/13108198/69556016-bbeec380-0fac-11ea-9f74-7815ff9da9fb.png)

Test #2 failures:
![image](https://user-images.githubusercontent.com/13108198/69556053-c8731c00-0fac-11ea-8d6e-a283dae286bc.png)
![image](https://user-images.githubusercontent.com/13108198/69556083-d6c13800-0fac-11ea-8154-74045e27f4c1.png)

**Comment by mobitar** [comment]
Thanks, fixed. One test was broken and should have been skipped: https://github.com/standardfile/sfjs/blob/master/test/sync.test.js#L636

Session history tests were missing a local data load.

As for sync discordance, those pass for me. Do they consistently fail for you (try with updated code).

<img width="590" alt="Screen Shot 2019-11-26 at 12 14 21 PM" src="https://user-images.githubusercontent.com/3277844/69660618-4df6da80-1046-11ea-88e3-1f78878c9ebc.png">

**Comment by raelb** [comment]
Yes, session history tests pass now.
Sync discordance seems to fail consistently.

Test #1:  (starting with 0 records in items and users)

![image](https://user-images.githubusercontent.com/13108198/69702876-d59d2180-10f8-11ea-9315-82bc7c23f14a.png)
![image](https://user-images.githubusercontent.com/13108198/69702894-de8df300-10f8-11ea-8a5b-04ab5f9674ab.png)

Test #2:
![image](https://user-images.githubusercontent.com/13108198/69702924-ee0d3c00-10f8-11ea-94aa-fc2e903d7589.png)
![image](https://user-images.githubusercontent.com/13108198/69702945-f796a400-10f8-11ea-9c23-0e858899cd62.png)
