### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by fahrradflucht** [standardfile/sfjs#5]
When I try to use this library in node I get the following error:

```
/.../node_modules/standard-file-js/dist/sfjs.js:5791
;var subtleCrypto = window.crypto ? window.crypto.subtle : null;
                    ^

ReferenceError: window is not defined
```

**Edit:**
I just noticed that the tests fail with the same error.

**Edit 2:**
Okay I realize that the tests are intended to be run in a browser.

**Comment by fahrradflucht** [comment]
Since this is unusable in node at the moment (and I'm not entirely sure if it is even itended to be used that way) I tried rolling the auth myself but I can't get it to work. I'm banging my had against this for hours.

Here is a gist of a minimal repro: https://gist.github.com/fahrradflucht/0a9776132869dbc9d369c90ef29f20fc

I'm always getting `{ error: { message: 'Invalid email or password.', status: 401 } }` back, but I'm pretty sure that the credentials aren't the problem since I can login with them in the web client. Any ideas what I got wrong?

**Comment by mobitar** [comment]
Hey sorry, just pushed out an [update](https://github.com/standardfile/sfjs/commit/197890a3721ae4b20d888e2af77249b65348b2e5) that should fix your original problem.

WebCrypto isn't available in Node, however, CryptoJS, which is bundled with SFJS, should work just fine. It'll use that by default.

**Comment by fahrradflucht** [comment]
Thanks. I figured that cryptojs thing myself this is why I thought of going the native node js crypto route. It works now but I got a really strange thing. See [my comment](https://gist.github.com/fahrradflucht/0a9776132869dbc9d369c90ef29f20fc#gistcomment-2655237). Any idea why that is?

**Comment by fahrradflucht** [comment]
Works!
