### ISSUE TITLE
No proper examples; README doc does not work as described

### ISSUE THREAD

**Issue by DinoChiesa** [standardfile/sfjs#7]
Hi, can you provide a proper hello world example in this repo? And also correct the README doc? 
I am trying to use the sfjs module from a node script, from the command line.  

First step: `npm install --save standard-file-js` 
After that, if I  try using the code you provide in the readme, specifically, 
```
  SFJS.crypto.computeEncryptionKeysForUser(password, authParams).then((keys) => {.. });
```
(BTW your README lacks the crypto in that line of code)

... I get an error related to the regeneratorRuntime that is possibly maybe somehow related to your use of babel. 

```
/Users/me/dev/standardnotes/cli/node_modules/standard-file-js/dist/sfjs.js:143
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(params) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/me/dev/standardnotes/cli/node_modules/standard-file-js/dist/sfjs.js:143:50
```
I have also done `npm install --save regenerator-runtime`, but that makes no difference. 
 
I'm not interested in babel or a regenerator runtime. I just want to 
- get auth params
- sign in
- update a note

I suppose that should take about 6 lines of code. What are the lines? 
Can you provide a suitable example?

**Comment by mobitar** [comment]
You seem to be on the right track. Just need to import the regeneratorRuntime:

## Integrating in a web app

1. Import these two files in your page, either via a packager like Grunt or Webpack, or via regular HTML script tags:

```javascript
<script src="regenerator.js"></script>
<script src="sfjs.js"></script>
```

(`regenerator.js` is only required in web environments. If in native environment, install the package independently via `npm install --save regenerator-runtime` and include it in your build.)
